name       : python-mygpoclient
version    : 1.8
release    : 6
source     :
    - https://github.com/gpodder/mygpoclient/archive/1.8.tar.gz : 65fcb3ab220a2ba2d32a77f969b423a2f663413b6c485b7b02e5a955b28e68d2
license    : GPL-3.0
component  : programming.python
summary    : gpodder client library
description: |
    Client library for the my.gpodder.org web service
builddeps  :
    - python-coverage
    - python-minimock
    - python-nose
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py3build
        nosetests-3.9 --cover-erase --with-coverage --with-doctest --cover-package=mygpoclient
    popd
