name       : python-mygpoclient
version    : '1.9'
release    : 8
source     :
    - https://github.com/gpodder/mygpoclient/archive/1.9.tar.gz : c1e990a6395acd5a5316be1cd9237c2669b9f6389d49f5740595c02049b95496
license    : GPL-3.0
homepage   : https://mygpoclient.readthedocs.io/en/latest/
component  : programming.python
summary    : gpodder client library
description: |
    Client library for the my.gpodder.org web service
builddeps  :
    - python-coverage
    - python-minimock
    - python-nose
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py3build
        nosetests-%python3_version% --cover-erase --with-coverage --with-doctest --cover-package=mygpoclient
    popd
