name       : python-mygpoclient
version    : 1.7
release    : 1
source     :
    - https://pypi.python.org/packages/source/m/mygpoclient/mygpoclient-1.7.tar.gz : 6a0b7b1fe2b046875456e14eda3e42430e493bf2251a64481cf4fd1a1e21a80e
license    : GPL-3.0
component  : programming.python 
summary    : gpodder client library 
description: |
    Client library for the my.gpodder.org web service
setup      : |
    %python_setup
install    : |
    %python_install
